### ISSUE TITLE
Highlighting text fails on demo

### ISSUE THREAD

**Issue by srchulo** [paperbits/paperbits-core#18]
If you go to the paperbits demo site, you cannot highlight text by clicking and dragging. The only thing I am able to highlight is by double clicking to highlight an entire paragraph.

**Comment by azaslonov** [comment]
Hi Adam, technically you double click on the text (which invokes text editor) and do the selection. The reason it's done like this is that we need to distinguish between dragging and selection gestures, and the dragging is a default one for all widgets.

Hope that makes sense.

**Comment by srchulo** [comment]
Oh, actually now I see that once I click in, I can highlight specific text. Not sure if that wasn't working before, or if I made a mistake. Thanks for the response! Seems to be working/make sense.

**Comment by azaslonov** [comment]
Got it, thanks.
