### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by myxxmikeyxx** [paperbits/paperbits-core#32]
I am having trouble finding where you declare the port to listen on.
When I run npm start it runs but I need the port to be 9000 not 8080.
Any help to point me to the file or location I need to add this?

**Comment by bronhy** [comment]
@myxxmikeyxx no reason to override the defaults but if you really need to this is how you do it.

Paperbits uses weback for serving the app.
Under the webpack.develop.js

```
    devServer: {
        hot: true,
        historyApiFallback: true,
        port: 9000, // this is added to the config
    },
```
then just run the server again.

These type of questions are better addressed under the community channel here
https://gitter.im/paperbits/discussions

**Comment by myxxmikeyxx** [comment]
Okay thank you. Sorry for the trouble.
