### ISSUE TITLE
Is the paperbits project alive? It seems to be used in azure apim devportal.

### ISSUE THREAD

**Issue by kincjf** [paperbits/paperbits-core#47]
hello. I am using azure apim devportal, and I was wondering if it is okay to use paperbits in other projects.

https://github.com/Azure/api-management-developer-portal

Although it has been confirmed that paperbits is being used as a core technology here, it has been found that the paperbits core has not been updated for several months.
  I wonder if paperbits are only being used for apim devportal?

**Comment by azaslonov** [comment]
Hi @kinder, the paperbits core has been updated on July. It's summer, people having vacations, etc. So, no worries here, it's not going to end anytime soon.

It's ok to use it in other projects, it's under MIT license.
