### ISSUE TITLE
Textbox widget loses focus after scrolling followed by mouse click

### ISSUE THREAD

**Issue by velsietis** [paperbits/paperbits-core#6]
I wasn't sure whether to log this against paperbits-core or paperbits-prosemirror, can't figure out the cause at the moment.

Reproduction Steps:
 - Go to https://demo.paperbits.io/ 
 - Click on one of the text blocks to start editing the text
 - Observe that you can click anywhere in the text box to re-position the cursor
 - Scroll with the mouse or scrollbar
 - Click on the textbox
 - **The text box has now lost focus and you have to close/reopen the editor to access again**

Some other details:
 - I've reproduced this in Chrome 75.0.3 and Edge 42.17134
 - Also reproduced it with the Azure API Developer Portal version not just the live demo
 - It's quite an annoying bug if you're editing a large text block

**Comment by azaslonov** [comment]
Hi @velsietis, thanks for reporting the issue. We'll fix this by end of the week.

**Comment by azaslonov** [comment]
Fixed. It will be included into the package of version 0.1.204.
